- name: pull request
  on:
    pull_request:
      types: [merged, opened, synchronize, review_request_]
      branches-ignore:
        - staging
        - master
- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: AKIASMZE24DE64AHUKFD
    aws-secret-access-key: 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
    aws-region: us-east-2
- name: Run CodeBuild
  uses: aws-actions/aws-codebuild-run-build@v1
  with:
    project-name: CodeBuildProjectName
  #  buildspec-override: path/to/buildspec.yaml
  #  env-vars-for-codebuild: |
  #    custom,
   #   requester,
   #   event-name
  env:

    custom: my environment variable
    requester: ${{ github.actor }}
    event-name: ${{ github.event_name }}
